### ISSUE TITLE
When using more recent version of lodash your library won't install

### ISSUE THREAD

**Issue by ziomio** [alexcheng1982/angular-timezone-select#3]
I am using Ruby on Rails and 'rails-assets' service to install bower packages.
When trying to install your package I get an error.
It happens because I use lodash 3.10.0 but you require 2.4.1

Bundler could not find compatible versions for gem "rails-assets-lodash":
  In Gemfile:
    rails-assets-angular-timezone-select (>= 0) ruby depends on
      rails-assets-lodash (~> 2.4.1) ruby

```
rails-assets-lodash (3.10.0)
```

**Comment by alexcheng1982** [comment]
I updated lodash to latest v3.10.1 in v1.0.3. This should fix you issue.

**Comment by ziomio** [comment]
Thanks, it fixed this issue, but now I get another error about using old version of moment-timezone.
I use moment-timezone 0.4.1 version but your library uses 0.3.0
Could you please update its version also?

 Bundler could not find compatible versions for gem "rails-assets-moment-timezone":
  In Gemfile:
    rails-assets-angular-timezone-select (>= 0) ruby depends on
      rails-assets-moment-timezone (~> 0.3.0) ruby

```
rails-assets-moment-timezone (0.4.1)
```

**Comment by ziomio** [comment]
Problems occur because of strict versioning requirements in bower.json file.
Would not it be better if you change `~` to '>=' sign?
i.e. instead of "moment-timezone": "~0.3.0" you will have "moment-timezone": ">=0.3.0"

More about versioning is here:
http://stackoverflow.com/questions/19030170/what-is-the-bower-version-syntax

# 

So please revert lodash version to 3.10.0, just use >= "greater than or equal to" sign instead of tilda (~)
