### ISSUE TITLE
I cannot use search feature

### ISSUE THREAD

**Issue by sutrixductran** [alexcheng1982/angular-timezone-select#6]
I have integrated your plugin in my project, but I couldn't use the search function, It always returned _No matches found_ when I typed something . Could you please help me to check it ?

**Comment by alexcheng1982** [comment]
Can you add your code which uses this component?

**Comment by sutrixductran** [comment]
Thank you for your reply,
I'm using default your plugin:
`<input timezone-select data-ng-model="timezone" country="country">`
And the result look like the example on your website:
http://alexcheng1982.github.io/angular-timezone-select/
![image](https://cloud.githubusercontent.com/assets/15906748/15286574/12c053f8-1b88-11e6-9ea4-923d5c626c79.png)
When I try to type: "A", I think it must be show all results - which have "A" character, example: "Asia/Kashgar UTC+06:00", but the result is:
![image](https://cloud.githubusercontent.com/assets/15906748/15286646/59178470-1b88-11e6-9ea0-ee097d6ee459.png)
Another, when I try to type: "C", the result is: 
![image](https://cloud.githubusercontent.com/assets/15906748/15286664/7b2d53e6-1b88-11e6-98b0-62c2db6d1956.png)
I think, problem is: the select2 only search the `optgroup`. Could you have a look and update ?

**Comment by alexcheng1982** [comment]
Thank you for the bug report. This issue is fixed in release 1.1.1.
